server:
  port: 6170
  servlet:
    context-path: /auth-service
spring:
  application:
    name: auth-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:host.docker.internal}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:password}


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: ${SPRING_DATASOURCE_SCHEMA_NAME:public}
      jdbc:
        time_zone: UTC
    open-in-view: false

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${SECURITY_JWT_EXPIRATION_TIME:300000}  #5 minutes in millisecond
