---
------------------ Travel Management Service TABLES ------------------
---

CREATE SCHEMA IF NOT EXISTS voyage_link_travel_management;

CREATE TABLE voyage_link_travel_management."location" (
                            deleted bool NOT NULL,
                            "version" int4 NOT NULL,
                            created_at timestamp(6) NOT NULL,
                            id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
                            updated_at timestamp(6) NULL,
                            city varchar(255) NOT NULL,
                            country varchar(255) NOT NULL,
                            location_code varchar(255) NOT NULL,
                            "name" varchar(255) NOT NULL,
                            CONSTRAINT location_location_code_key UNIQUE (location_code),
                            CONSTRAINT location_pkey PRIMARY KEY (id)
);


CREATE TABLE voyage_link_travel_management.transportation (
                                deleted bool NOT NULL,
                                "version" int4 NOT NULL,
                                created_at timestamp(6) NOT NULL,
                                destination_location_id int8 NULL,
                                id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
                                origin_location_id int8 NULL,
                                updated_at timestamp(6) NULL,
                                transportation_type varchar(255) NULL,
                                CONSTRAINT transportation_pkey PRIMARY KEY (id),
                                CONSTRAINT transportation_transportation_type_check CHECK (((transportation_type)::text = ANY ((ARRAY['FLIGHT'::character varying, 'BUS'::character varying, 'SUBWAY'::character varying, 'UBER'::character varying])::text[]))),
	CONSTRAINT fk_transportation_destination_location FOREIGN KEY (destination_location_id) REFERENCES "location"(id),
	CONSTRAINT fk_transportation_origin_location FOREIGN KEY (origin_location_id) REFERENCES "location"(id)
);

CREATE TABLE voyage_link_travel_management.transportation_operating_days (
                                               operating_days int4 NULL,
                                               transportation_id int8 NOT NULL,
                                               CONSTRAINT fk_transportation_operating_days FOREIGN KEY (transportation_id) REFERENCES transportation(id)
);
