server:
  port: 6180
  servlet:
    context-path: /travel-management-service
spring:
  application:
    name: /travel-management-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:host.docker.internal}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:password}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: ${SPRING_DATASOURCE_SCHEMA_NAME:voyage_link_travel_management}
      jdbc:
        time_zone: UTC

service:
  auth:
    url: ${AUTH_SERVICE_BASE_URL:http://host.docker.internal:6190}