---
------------------ Auth Service TABLES ------------------
---

CREATE SCHEMA IF NOT EXISTS voyage_link_auth;

CREATE TABLE IF NOT EXISTS voyage_link_auth."user" (
                                         deleted bool NOT NULL,
                                         "version" int4 NOT NULL,
                                         created_at timestamp(6) NOT NULL,
                                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
                                         updated_at timestamp(6) NULL,
                                         firstname varchar(255) NOT NULL,
                                         identification_number varchar(255) NOT NULL,
                                         lastname varchar(255) NOT NULL,
                                         "password" varchar(255) NOT NULL,
                                         CONSTRAINT user_identification_number_key UNIQUE (identification_number),
                                         CONSTRAINT user_pkey PRIMARY KEY (id)
);
